USE `netland`;

INSERT INTO films (id, title, duration, date, country, description, trailer)
VALUES (1, 'Sonic The Hedgehog', '1 u 40 m', '2020', 'USA', 'Sonic the Hedgehog is a 2020 action-adventure comedy film based on the video game franchise published by Sega.', 'szby7ZHLnkA');
INSERT INTO films (id, title, duration, date, country, description, trailer)
VALUES (2, 'The Call of the Wild', '1 u 40 m', '2020', 'USA', 'he Call of the Wild is a 2020 American adventure film based on the Jack London 1903 novel of the same name and Twentieth Century Pictures'' previous 1935 film adaptation. The film is directed by Chris Sanders, in his live-action directorial debut, written by Michael Green, and stars Harrison Ford, Dan Stevens, Omar Sy, Karen Gillan, Bradley Whitford, and Colin Woodell. Set in the 1890s Klondike Gold Rush, a dog named Buck is stolen from his home in California and sent to the Yukon, where he befriends an old man and begins a life-altering adventure.', 'h1LG9So2ZBk');
INSERT INTO films (id, title, duration, date, country, description, trailer)
VALUES (3, 'Dolittle (The Voyage of Doctor Dolittle)', '1 u 41 m', '2020', 'USA', 'Dolittle (also referred to as The Voyage of Doctor Dolittle) is a 2020 American fantasy adventure film directed by Stephen Gaghan from a screenplay by Gaghan, Dan Gregor, and Doug Mand, based on a story by Thomas Shepherd. A reboot of the original Doctor Dolittle film and its modern comedy counterparts, the film is based on the titular character created by Hugh Lofting, and primarily inspired by The Voyages of Doctor Dolittle, the author''s second Doctor Dolittle book. Robert Downey Jr. stars as the title character, alongside Antonio Banderas and Michael Sheen in live action roles, and a voice cast including Emma Thompson, Rami Malek, John Cena, Kumail Nanjiani, Octavia Spencer, Tom Holland, Craig Robinson, Ralph Fiennes, Selena Gomez, and Marion Cotillard.', 'zjm6rDgKNMY');
INSERT INTO films (id, title, duration, date, country, description, trailer)
VALUES (4, 'Star Wars: The Rise of Skywalker', '2 u 22 m', '2019', 'USA', 'The Rise of Skywalker follows Rey, Finn, and Poe Dameron as they lead the Resistance''s final stand against Kylo Ren and the First Order, who are now aided by the return of the deceased galactic emperor, Palpatine.', '8Qn_spdM5Zg');
INSERT INTO films (id, title, duration, date, country, description, trailer)
VALUES (5, 'Avengers: Endgame', '3 u 2 m', '2019', 'USA', 'Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2012''s The Avengers, 2015''s Avengers: Age of Ultron, and 2018''s Avengers: Infinity War, and the twenty-second film in the Marvel Cinematic Universe (MCU).', 'TcMBFSGVi1c');